name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  plan:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7  # Adjust to your desired Terraform version

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./gcp
        
      # Plan Terraform
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./gcp

  # Manual Approval Step
  approval:
    name: Manual Approval
    needs: plan
    runs-on: ubuntu-latest

    steps:
      - name: Await Manual Approval
        run: |
          echo "Please approve this job manually in the GitHub Actions UI."
          echo "Once approved, the 'apply' step will proceed."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Terraform Apply after Approval
  apply:
    name: Terraform Apply
    needs: approval
    runs-on: ubuntu-latest

    steps:
      # Checkout the code again (required because each job is isolated)
      - name: Checkout Code
        uses: actions/checkout@v3

      # Change directory to 'gcp'
      - name: Change Directory to GCP
        run: cd gcp

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7  # Adjust to your desired Terraform version

      # Apply Terraform
      - name: Terraform Apply
        env:
          TF_VAR_example_variable: ${{ secrets.TF_VAR_EXAMPLE_VARIABLE }}
        run: terraform apply -auto-approve tfplan
