name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7  # Adjust to your desired Terraform version

      - name: list current directory
        run: ls -al ./
        
      # Change directory to 'gcp'
      - name: Change Directory to GCP
        run: cd gcp
        
      - name: list current directory
        run: ls -al ./

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Plan Terraform
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Apply Terraform (requires approval)
      - name: Terraform Apply
        if: github.event_name == 'pull_request'
        env:
          TF_VAR_example_variable: ${{ secrets.TF_VAR_EXAMPLE_VARIABLE }}
        run: |
          echo "To apply changes, a manual approval is required."
      #    terraform apply -auto-approve tfplan

