name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  plan:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7  # Adjust to your desired Terraform version

      # Setup Google Cloud SDK
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          export_default_credentials: true

      # Authenticate using GCP credentials
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # save GCP credentials JSON
      - name: Create credentials file
        run: echo "${{ secrets.GCP_CREDENTIALS }}" > gcp-credentials.json
      
      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./gcp
        
      # Plan Terraform
      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan -var="credentials_file_path=${{ github.workspace }}/gcp-credentials.json"
        working-directory: ./gcp
        env:
          TF_LOG: DEBUG
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        timeout-minutes: 10

  # Manual Approval Step
  approval:
    name: Manual Approval
    needs: plan
    runs-on: ubuntu-latest

    steps:
      - name: Await Manual Approval
        run: |
          echo "Please approve this job manually in the GitHub Actions UI."
          echo "Once approved, the 'apply' step will proceed."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Terraform Apply after Approval
  apply:
    name: Terraform Apply
    needs: approval
    runs-on: ubuntu-latest

    steps:
      # Checkout the code again (required because each job is isolated)
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7  # Adjust to your desired Terraform version

      # Setup Google Cloud SDK
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          export_default_credentials: true

      # Authenticate using GCP credentials
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Apply Terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./gcp
        env:
          TF_LOG: DEBUG
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        timeout-minutes: 10
