name: Workflow with Approval

on:
  pull_request:
    types: [opened, synchronize]

  workflow_dispatch: # Enables manual triggers for approval

jobs:
  # First Job: Automatically triggered for tasks
  workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run soft-error-prone task
        id: soft_task
        run: |
          echo "Running task with potential soft error..."
          # Simulate a soft error
          exit 1
        continue-on-error: true

      - name: Notify for Approval
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = github.context.payload.pull_request.number;
            const owner = github.context.repo.owner;
            const repo = github.context.repo.repo;

            await github.rest.issues.createComment({
              issue_number,
              owner,
              repo,
              body: "Workflow requires manual approval. Please trigger the next step using workflow_dispatch."
            });

  # Second Job: Requires manual approval to proceed
  approval:
    runs-on: ubuntu-latest
    needs: workflow
    if: ${{ github.event_name == 'workflow_dispatch' }} # Runs only on manual trigger

    steps:
      - name: Proceed after manual approval
        run: echo "Manual approval granted. Continuing workflow."
