name: PR Workflow with Approval

on:
  # pull_request:
  #   types: [opened, synchronize]

  workflow_dispatch: # Enables manual triggers for approval

jobs:
  # First Job: Automatically triggered for tasks
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run soft-error-prone task
        id: soft_task
        run: |
          echo "Running task with potential soft error..."
          # Simulate a soft error
          exit 1
        continue-on-error: true

  manual-approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: build
    if: success() # Only proceed if terraform-plan job succeeds

    steps:
      - name: Await Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: udaysingh007
          minimum-approvals: 1
          issue-title: "Manual Approval Required for Terraform Apply"
          issue-body: "Please approve or deny the deployment."
          
