name: Workflow with Approval

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
  
jobs:
  workflow:
    runs-on: ubuntu-latest

    steps:
      # Task 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Task 2: Run a task that may return a soft error
      - name: Run soft-error-prone task
        id: soft_task
        run: |
          echo "Running task with potential soft error..."
          # Simulate a soft error (non-zero exit but continue execution)
          exit 1
        continue-on-error: true

  approval:
    runs-on: ubuntu-latest
    needs: workflow

    steps:
      # Approval Step (Manual Interaction)
      - name: Approval Step
        uses: actions/github-script@v6
        with:
          script: |
            const context = get Gitub
